easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\Recipe
        - App\Entity\Reviews
        - App\Entity\Step
        - App\Entity\Units
        - App\Entity\KitchenTools
        - App\Entity\Ingredient
        - App\Entity\Tag
        - App\Entity\Comments
        - App\Entity\User

